security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        philippe:
            entity: { class: App\Entity\Login, property: username_login }
        #in_memory:
            #memory:
                #users:
                    #admin:
                        #password: $2y$12$xIVM8wRtdTsuA2hjxk4rhO7idJ6CWQlIbp//TRzMUwhxEvs187vXK
                        #roles: ['ROLE_ADMIN']
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: philippe
            anonymous: ~
                     
            form_login:
                login_path: security_login
                check_path: security_login_check
                username_parameter: username_login
                password_parameter: password_login
            #logout:
            #    path:       logout
            #    target:     login
            # field names for the username and password fields
            
            # by default, the login form *must* be a POST, not a GET
            #post_only:      true
            #remember_me:    false

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

      

    encoders:
        #Symfony\Component\Security\Core\User\Members: plaintext
        App\Entity\Members: 
            algorithm: bcrypt  
            cost: 12
        App\Entity\Login: 
            algorithm: bcrypt  
            cost: 12
    
    access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
