#vich_uploader :
#    db_driver : orm
#    templating: true
#    twig: true
#    form: true
#
#    mappings:
#        product_image:
#            uri_prefix: /img
#            upload_destination: '%kernel.project_dir%/public/img'
#
#            inject_on_load: false
#            delete_on_update: true
#            delete_on_remove: true