# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'
    env(DATABASE_HOST): localhost
    images_directory: '%kernel.project_dir%/public/img/profil'
    adverts_directory: '%kernel.project_dir%/public/img/advert'
   

services:
    app.security.login_authenticator:
        class: App\Security\LoginAuthenticator
        autowire: true
        arguments: ["@router", "@security.password_encoder"]
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    
    App\Service\ImageUploader:
        arguments:
            $targetDirectoryProfil: '%images_directory%'
            $targetDirectoryAdvert: '%adverts_directory%'

    App\BranchLoader\GitLoader:
        arguments:
            ['%kernel.project_dir%']

    App\DataCollector\GitDataCollector:
        tags:
            -
                name:     data_collector
                template: 'data_collector/git_data.html.twig'
                # must match the value returned by the getName() method
                id: 'app.git_data_collector'
        public: false
    

    #App\EventListener\ImageUploadListener:
    #    tags:
    #        - { name: doctrine.event_listener, event: prePersist }
    #        - { name: doctrine.event_listener, event: preUpdate }
    #         - { name: doctrine.event_listener, event: postLoad }
            

    #image_listener:
    #    class: App\EventListener\ImageUploadListener
    #    arguments: ['@image_uploader']
    #    tags:
    #        - { name: doctrine.event_listener, event: prePersist }
    #        - { name: doctrine.event_listener, event: preUpdate }
    
    